#!/usr/bin/env node
// The committed exports are deterministic projections of palette/zirconium.json.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = readFileSync(resolve(root, 'palette/zirconium.json'), 'utf8');
const palette = JSON.parse(source);
const hex = /^#[0-9a-f]{6}$/i;
const names = ['black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'white'];
const luaReserved = new Set(['and', 'break', 'do', 'else', 'elseif', 'end', 'false', 'for', 'function', 'goto', 'if', 'in', 'local', 'nil', 'not', 'or', 'repeat', 'return', 'then', 'true', 'until', 'while']);
const indexColors = [];
const levels = [0, 95, 135, 175, 215, 255];
for (let r = 0; r < 6; r++) for (let g = 0; g < 6; g++) for (let b = 0; b < 6; b++) {
  indexColors.push([16 + 36 * r + 6 * g + b, [levels[r], levels[g], levels[b]]]);
}
for (let i = 0; i < 24; i++) indexColors.push([232 + i, [8 + 10 * i, 8 + 10 * i, 8 + 10 * i]]);
function indexOf(color) {
  const rgb = [1, 3, 5].map(i => parseInt(color.slice(i, i + 2), 16));
  return indexColors.reduce((best, [index, val]) => {
    const distance = rgb.reduce((sum, part, i) => sum + (part - val[i]) ** 2, 0);
    return distance < best.distance ? { index, distance } : best;
  }, { index: 16, distance: Infinity }).index;
}
function allColors(value) {
  if (typeof value === 'string') return hex.test(value) ? [value.toLowerCase()] : [];
  if (Array.isArray(value)) return value.flatMap(allColors);
  if (value && typeof value === 'object') return Object.values(value).flatMap(allColors);
  return [];
}
function lua(value, indent = 0) {
  const pad = '  '.repeat(indent);
  if (typeof value === 'string') return `'${value}'`;
  if (typeof value === 'number') return String(value);
  if (Array.isArray(value)) return `{ ${value.map(x => lua(x)).join(', ')} }`;
  return `{\n${Object.entries(value).map(([key, val]) => `${pad}  ${/^[a-zA-Z_][a-zA-Z_0-9]*$/.test(key) && !luaReserved.has(key) ? key : `[${lua(key)}]`} = ${lua(val, indent + 1)},`).join('\n')}\n${pad}}`;
}
function alacritty(p) {
  const block = (name, keys) => `[colors.${name}]\n${keys.map(([k, v]) => `${k} = "${v}"`).join('\n')}\n\n`;
  return '# Generated by scripts/generate.mjs — edit palette/zirconium.json instead.\n' +
    block('primary', [['background', p.surface.bg], ['foreground', p.text.primary]]) +
    block('cursor', [['text', p.text.inverse], ['cursor', p.ui.cursor]]) +
    block('selection', [['text', p.ui.selectionFg], ['background', p.surface.selection]]) +
    block('normal', names.map((name, i) => [name, p.ansi.normal[i]])) +
    block('bright', names.map((name, i) => [name, p.ansi.bright[i]]));
}
function foot(p, variant) {
  return '# Generated by scripts/generate.mjs — edit palette/zirconium.json instead.\ninitial-color-theme=' + variant + '\n[colors-' + variant + ']\n' +
    [`foreground=${p.text.primary}`, `background=${p.surface.bg}`, `selection-foreground=${p.ui.selectionFg}`, `selection-background=${p.surface.selection}`, `cursor=${p.text.inverse} ${p.ui.cursor}`,
      ...p.ansi.normal.map((c, i) => `regular${i}=${c}`),
      ...p.ansi.bright.map((c, i) => `bright${i}=${c}`)].map(s => s.replaceAll('#', '')).join('\n') + '\n';
}
function kitty(p) {
  return '# Generated by scripts/generate.mjs — edit palette/zirconium.json instead.\n' +
    [`foreground ${p.text.primary}`, `background ${p.surface.bg}`, `cursor ${p.ui.cursor}`, `cursor_text_color ${p.text.inverse}`, `selection_foreground ${p.ui.selectionFg}`, `selection_background ${p.surface.selection}`,
      ...[...p.ansi.normal, ...p.ansi.bright].map((c, i) => `color${i} ${c}`)].join('\n') + '\n';
}
for (const variant of ['dark', 'light']) {
  const p = palette[variant];
  for (const section of ['surface', 'text', 'syntax', 'diagnostic', 'ui']) {
    for (const [key, val] of Object.entries(p[section])) {
      if (!hex.test(val)) throw new Error(`${variant}.${section}.${key} is not a hex color`);
    }
  }
  for (const ramp of ['normal', 'bright']) {
    if (p.ansi[ramp].length !== 8 || p.ansi[ramp].some(c => !hex.test(c))) throw new Error(`${variant} ANSI ${ramp} must contain eight hex colors`);
  }
}
const uniqueColors = [...new Set(allColors({ dark: palette.dark, light: palette.light }))].sort();
const indices = Object.fromEntries(uniqueColors.map(color => [color, indexOf(color)]));
const outputs = {
  'lua/zirconium/palette.lua': '-- Generated by scripts/generate.mjs — edit palette/zirconium.json instead.\nreturn ' + lua({ dark: palette.dark, light: palette.light, cterm: indices }) + '\n',
  'site/src/lib/palette.json': JSON.stringify(palette, null, 2) + '\n',
};
for (const variant of ['dark', 'light']) {
  for (const [app, extension, render] of [['alacritty', 'toml', alacritty], ['foot', 'ini', foot], ['kitty', 'conf', kitty]]) {
    outputs[`terminal/${app}/zirconium-${variant}.${extension}`] = render(palette[variant], variant);
  }
}
let mismatches = 0;
for (const [path, content] of Object.entries(outputs)) {
  const full = resolve(root, path);
  if (process.argv.includes('--check')) {
    let actual;
    try { actual = readFileSync(full, 'utf8'); } catch { actual = null; }
    if (actual !== content) { console.error(`Out of date: ${path}`); mismatches++; }
  } else {
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, content);
    console.log(`Generated ${path}`);
  }
}
if (mismatches) process.exitCode = 1;
else if (process.argv.includes('--check')) console.log('All palette exports are current.');
